# Generated by Django 5.2.4 on 2025-07-28 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='rail_lines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_id', models.IntegerField()),
                ('route_code', models.CharField(max_length=100)),
                ('route_color', models.CharField(max_length=6)),
                ('route_text_color', models.CharField(max_length=6)),
                ('route_url', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('pdf_file_url', models.CharField(max_length=255)),
                ('iconography_url', models.CharField(max_length=255)),
                ('terminal_1', models.CharField(max_length=100)),
                ('terminal_2', models.CharField(max_length=100)),
                ('description_0', models.CharField(max_length=100)),
                ('description_1', models.CharField(max_length=100)),
                ('travel_direction_0', models.CharField(max_length=100)),
                ('travel_direction_1', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Rail Lines',
            },
        ),
    ]
