# Generated by Django 5.2.4 on 2025-07-29 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='rail_lines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_id', models.IntegerField()),
                ('route_code', models.CharField(max_length=100)),
                ('route_color', models.CharField(max_length=6)),
                ('route_text_color', models.CharField(max_length=6)),
                ('route_url', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('pdf_file_url', models.CharField(max_length=255)),
                ('iconography_url', models.CharField(max_length=255)),
                ('terminal_1', models.CharField(max_length=100)),
                ('terminal_2', models.CharField(max_length=100)),
                ('description_0', models.CharField(max_length=100)),
                ('description_1', models.CharField(max_length=100)),
                ('travel_direction_0', models.CharField(max_length=100)),
                ('travel_direction_1', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Rail Lines',
            },
        ),
        migrations.CreateModel(
            name='station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stop_name', models.CharField(max_length=100)),
                ('stop_lat', models.FloatField()),
                ('stop_lon', models.FloatField()),
                ('parent_station', models.IntegerField()),
                ('tpis_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='StopTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrival_time', models.CharField(max_length=100)),
                ('departure_time', models.CharField(max_length=100)),
                ('stop_id', models.IntegerField()),
                ('stop_sequence', models.IntegerField()),
                ('stop_headsign', models.CharField(max_length=255)),
                ('pickup_type', models.IntegerField()),
                ('drop_off_type', models.IntegerField()),
            ],
        ),
    ]
