# Generated by Django 5.2.4 on 2025-07-28 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rail', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rail_lines',
            name='created_at',
        ),
    ]
