# Generated by Django 5.2.4 on 2025-07-28 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rail', '0002_remove_rail_lines_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stop_name', models.CharField(max_length=100)),
                ('stop_lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('stop_lon', models.DecimalField(decimal_places=6, max_digits=9)),
                ('parent_station', models.IntegerField()),
                ('tpis_name', models.CharField(max_length=100)),
            ],
        ),
    ]
